############  PART OFF  DOCKER-COMPOSE.YML  #############
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
version: '2'
services:

#################### DATABASE PHPMYADMIN ########################
#  phpmyadmin:
#   image: phpmyadmin/phpmyadmin
#################### DATABASE MARIADB ########################
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - './mariadb_data:/bitnami/mariadb'
    hostname: mariadb
    networks: 
      - moodlenets

############## MOODLE WEB # 1 ###################
  moodle1:
    image: docker.io/bitnami/moodle:4.1
    container_name: moodle1
    restart: always
    ports:
      - '8001:8080'
      - '8041:8443'
      - '8021:22'
  
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './moodle_data:/bitnami/moodle'
      - './moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
    hostname: moodle1
    networks: 
      - moodlenets

############## MOODLE WEB #2 ###################
  moodle2:
    image: docker.io/bitnami/moodle:4.1
    container_name: moodle2
    restart: always
    ports:
      - '8002:8080'
      - '8042:443'
      - '8022:22'
    
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './moodle_data:/bitnami/moodle'
      - './moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
    hostname: moodle2
    networks: 
      - moodlenets

############## MOODLE WEB # 3 ###################
  moodle3:
    image: docker.io/bitnami/moodle:4.1
    container_name: moodle3
    restart: always
    ports:
      - '8003:8080'
      - '8043:443'
      - '8023:22'
   
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './moodle_data:/bitnami/moodle'
      - './moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
    hostname: moodle3
    networks: 
      - moodlenets

############### BALANCING WEB [HAPROXY] ##################
  haproxy:
    image: haproxy:bullseye
    container_name: haproxy
    restart: always
    ports:
      - '80:80'
      - '7743:443'
      - '7722:22'
    volumes:
      -  ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
 
    depends_on:
      - moodle1
      - moodle2
      - moodle3
    hostname: haproxy
    networks: 
      - moodlenets

networks:
  moodlenets:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
######################################################
